import React, { useState } from 'react';
import { FileText, Save, Upload, AlertCircle, CheckCircle, PlusCircle, Cable } from 'lucide-react';
import { createChangeRequest } from '@/services/api';

export const ChangeManagement: React.FC = () => {
    // --- FORM STATE ---
    const [loading, setLoading] = useState(false);
    const [success, setSuccess] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [circuitCategory, setCircuitCategory] = useState<'new' | 'existing' | ''>('');
    const [existingAction, setExistingAction] = useState<'Upgrade/Downgrade' | 'Shifting' | 'Decommission' | ''>('');
    const [formData, setFormData] = useState({
        salesforce_region: '', account_name: '',
        site_id: '', bandwidth: '', new_circuit_type: '', site_address: '', contract_term: '',
        current_circuit_id: '', existing_bandwidth: '', new_bandwidth: '',
        circuit_id_move: '', new_address: '', old_circuit_address: '',
        decommission_circuit_id: '', decommission_date: '', decommission_notice_period: '', circuit_details: '', reason_for_decommission: '',
        new_intl_dom_split: '', notes: ''
    });
    const [file, setFile] = useState<File | null>(null);

    // --- FORM HANDLERS ---
    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };
    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) setFile(e.target.files[0]);
    };
    const handleCategoryChange = (category: 'new' | 'existing') => {
        setCircuitCategory(category);
        setExistingAction('');
    };
    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError(null);
        setSuccess(false);
        let changeType = circuitCategory === 'new' ? 'Add New Sites' : existingAction;
        try {
            const dataToSubmit = new FormData();
            dataToSubmit.append('data', JSON.stringify({ ...formData, change_type: changeType, id: `CR-${Date.now()}`, status: 'New Request' }));
            if (file) dataToSubmit.append('file', file);
            await createChangeRequest(dataToSubmit);
            setSuccess(true);
            setCircuitCategory('');
            setExistingAction('');
            setFormData({ salesforce_region: '', account_name: '', site_id: '', bandwidth: '', new_circuit_type: '', site_address: '', contract_term: '', current_circuit_id: '', existing_bandwidth: '', new_bandwidth: '', circuit_id_move: '', new_address: '', old_circuit_address: '', decommission_circuit_id: '', decommission_date: '', decommission_notice_period: '', circuit_details: '', reason_for_decommission: '', new_intl_dom_split: '', notes: '' });
            setFile(null);
        } catch (err) { setError("Failed to submit."); console.error(err); }
        finally { setLoading(false); }
    };

    const showForm = circuitCategory === 'new' || (circuitCategory === 'existing' && existingAction);

    // --- Render Helpers (Form Fields) ---
    const renderCommonFields = () => (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            <div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Salesforce Region</label><select name="salesforce_region" value={formData.salesforce_region} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" required><option value="">Select Region</option><option value="Americas">Americas</option><option value="EMEA">EMEA</option><option value="APAC">APAC</option></select></div>
            <div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Account Name</label><input type="text" name="account_name" value={formData.account_name} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" placeholder="Enter Account Name" required /></div>
        </div>
    );
    const renderAddNewSitesFields = () => (<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in slide-in-from-top-4"><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Site ID</label><input type="text" name="site_id" value={formData.site_id} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Bandwidth</label><input type="text" name="bandwidth" value={formData.bandwidth} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">New Circuit Type</label><input type="text" name="new_circuit_type" value={formData.new_circuit_type} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div className="md:col-span-2"><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Site Address</label><input type="text" name="site_address" value={formData.site_address} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Contract Term (Months)</label><input type="number" name="contract_term" value={formData.contract_term} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">New Intl/Domestic Split</label><input type="text" name="new_intl_dom_split" value={formData.new_intl_dom_split} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div></div>);
    const renderUpgradeDowngradeFields = () => (<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in slide-in-from-top-4"><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Current Circuit ID</label><input type="text" name="current_circuit_id" value={formData.current_circuit_id} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div className="md:col-span-2"><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Address</label><input type="text" name="site_address" value={formData.site_address} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Existing Bandwidth</label><input type="text" name="existing_bandwidth" value={formData.existing_bandwidth} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">New Bandwidth</label><input type="text" name="new_bandwidth" value={formData.new_bandwidth} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">New Intl/Domestic Split</label><input type="text" name="new_intl_dom_split" value={formData.new_intl_dom_split} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div></div>);
    const renderShiftingFields = () => (<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in slide-in-from-top-4"><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Circuit ID (Move)</label><input type="text" name="circuit_id_move" value={formData.circuit_id_move} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div className="md:col-span-2"><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">New Address</label><input type="text" name="new_address" value={formData.new_address} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div className="md:col-span-3"><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Old Circuit Address</label><input type="text" name="old_circuit_address" value={formData.old_circuit_address} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Existing Bandwidth</label><input type="text" name="existing_bandwidth" value={formData.existing_bandwidth} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">New Bandwidth</label><input type="text" name="new_bandwidth" value={formData.new_bandwidth} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">New Intl/Domestic Split</label><input type="text" name="new_intl_dom_split" value={formData.new_intl_dom_split} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div></div>);
    const renderDecommissionFields = () => (<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in slide-in-from-top-4"><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Decommission Circuit ID</label><input type="text" name="decommission_circuit_id" value={formData.decommission_circuit_id} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Decommission Date</label><input type="date" name="decommission_date" value={formData.decommission_date} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Notice Period</label><input type="text" name="decommission_notice_period" value={formData.decommission_notice_period} onChange={handleChange} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div className="md:col-span-3"><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Circuit Details</label><textarea name="circuit_details" value={formData.circuit_details} onChange={handleChange} rows={2} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div><div className="md:col-span-3"><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Reason for Decommission</label><textarea name="reason_for_decommission" value={formData.reason_for_decommission} onChange={handleChange} rows={2} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" /></div></div>);

    return (
        <div className="h-full flex flex-col p-8 overflow-y-auto custom-scrollbar">
            <div className="mb-6">
                <h2 className="text-2xl font-bold text-slate-800 dark:text-charcoal-50 flex items-center gap-2">
                    <FileText className="text-purple-600" />
                    MIC Change Management
                </h2>
                <p className="text-slate-500 dark:text-gray-400 mt-1">Submit circuit change requests.</p>
            </div>

            {/* Form View */}
            <form onSubmit={handleSubmit} className="bg-white dark:bg-charcoal-800 rounded-3xl p-8 border border-slate-200 dark:border-charcoal-700 shadow-sm max-w-5xl animate-in fade-in">
                {error && <div className="mb-6 p-4 bg-rose-50 border border-rose-200 text-rose-600 rounded-xl flex items-center gap-2"><AlertCircle size={20} /> {error}</div>}
                {success && <div className="mb-6 p-4 bg-emerald-50 border border-emerald-200 text-emerald-600 rounded-xl flex items-center gap-2"><CheckCircle size={20} /> Request submitted successfully!</div>}
                <div className="mb-8"><label className="block text-sm font-semibold text-slate-700 dark:text-gray-300 mb-4">Select Circuit Category</label><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><button type="button" onClick={() => handleCategoryChange('new')} className={`flex items-center gap-4 p-6 rounded-2xl border-2 transition-all duration-200 text-left ${circuitCategory === 'new' ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20 shadow-lg' : 'border-slate-200 dark:border-charcoal-700 hover:border-slate-300'}`}><div className={`p-3 rounded-xl ${circuitCategory === 'new' ? 'bg-purple-600 text-white' : 'bg-slate-100 dark:bg-charcoal-700 text-slate-500'}`}><PlusCircle size={24} /></div><div><p className={`font-semibold ${circuitCategory === 'new' ? 'text-purple-700 dark:text-purple-300' : 'text-slate-700 dark:text-gray-200'}`}>New Circuit</p><p className="text-xs text-slate-500 dark:text-gray-400">Add a new circuit or site.</p></div></button><button type="button" onClick={() => handleCategoryChange('existing')} className={`flex items-center gap-4 p-6 rounded-2xl border-2 transition-all duration-200 text-left ${circuitCategory === 'existing' ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20 shadow-lg' : 'border-slate-200 dark:border-charcoal-700 hover:border-slate-300'}`}><div className={`p-3 rounded-xl ${circuitCategory === 'existing' ? 'bg-purple-600 text-white' : 'bg-slate-100 dark:bg-charcoal-700 text-slate-500'}`}><Cable size={24} /></div><div><p className={`font-semibold ${circuitCategory === 'existing' ? 'text-purple-700 dark:text-purple-300' : 'text-slate-700 dark:text-gray-200'}`}>Existing Circuit</p><p className="text-xs text-slate-500 dark:text-gray-400">Modify or decommission.</p></div></button></div></div>
                {circuitCategory === 'existing' && (<div className="mb-8 animate-in slide-in-from-top-4"><label className="block text-sm font-semibold text-slate-700 dark:text-gray-300 mb-4">Select Action</label><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{(['Upgrade/Downgrade', 'Shifting', 'Decommission'] as const).map(action => (<button key={action} type="button" onClick={() => setExistingAction(action)} className={`p-4 rounded-xl border-2 font-medium transition-all ${existingAction === action ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20 text-purple-700' : 'border-slate-200 dark:border-charcoal-700 text-slate-600 dark:text-gray-300'}`}>{action}</button>))}</div></div>)}
                {showForm && (<div className="border-t border-slate-100 dark:border-charcoal-700 pt-8 animate-in slide-in-from-bottom-4">{renderCommonFields()}<div className="my-6">{circuitCategory === 'new' && renderAddNewSitesFields()}{circuitCategory === 'existing' && existingAction === 'Upgrade/Downgrade' && renderUpgradeDowngradeFields()}{circuitCategory === 'existing' && existingAction === 'Shifting' && renderShiftingFields()}{circuitCategory === 'existing' && existingAction === 'Decommission' && renderDecommissionFields()}</div><div className="grid grid-cols-1 gap-6 mb-6"><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Notes</label><textarea name="notes" value={formData.notes} onChange={handleChange} rows={3} className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-charcoal-600 dark:bg-charcoal-900" placeholder="Additional details..." /></div><div><label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Upload Inventory List (Optional)</label><label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed border-slate-300 dark:border-charcoal-600 rounded-xl cursor-pointer bg-slate-50 dark:bg-charcoal-900 hover:bg-slate-100 transition-colors"><div className="flex flex-col items-center justify-center pt-5 pb-6"><Upload className="w-8 h-8 mb-3 text-slate-400" /><p className="mb-2 text-sm text-slate-500"><span className="font-semibold">Click to upload</span></p><p className="text-xs text-slate-400">{file ? file.name : "Excel, CSV or PDF"}</p></div><input type="file" className="hidden" onChange={handleFileChange} /></label></div></div><div className="flex justify-end pt-4"><button type="submit" disabled={loading} className="flex items-center gap-2 px-6 py-3 bg-purple-600 text-white rounded-xl font-medium hover:bg-purple-700 disabled:opacity-50 shadow-lg">{loading ? 'Submitting...' : <><Save size={18} /> Submit Request</>}</button></div></div>)}
            </form>
        </div>
    );
};
